# Generated by Django 6.0.1 on 2026-08-13 20:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("budget", "0002_budgetlimit"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(
                fields=["user", "date"], name="budget_tran_user_id_fcff6a_idx"
            ),
        ),
    ]
