# Generated by Django 6.0.1 on 2026-08-14 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("budget", "0003_transaction_budget_tran_user_id_fcff6a_idx"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="icon",
            field=models.CharField(blank=True, default="", max_length=32),
        ),
    ]
