# Generated by Django 6.0.1 on 2026-09-10 14:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("budget", "0009_recurringtransaction"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="color",
            field=models.CharField(
                blank=True,
                default="",
                max_length=20,
                validators=[
                    django.core.validators.RegexValidator(
                        "^#[0-9a-fA-F]{6}$",
                        "Enter a color as a 6-digit hex code, e.g. #6366f1.",
                    )
                ],
            ),
        ),
    ]
