# Generated by Django 6.0.1 on 2026-09-10 14:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("budget", "0010_alter_category_color"),
    ]

    operations = [
        migrations.AlterField(
            model_name="budgetlimit",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="budget_limits",
                to="budget.category",
            ),
        ),
        migrations.AlterField(
            model_name="recurringtransaction",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="recurring_transactions",
                to="budget.category",
            ),
        ),
        migrations.AlterField(
            model_name="recurringtransaction",
            name="wallet",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="recurring_transactions",
                to="budget.wallet",
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="transactions",
                to="budget.category",
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="wallet",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="transactions",
                to="budget.wallet",
            ),
        ),
    ]
