# Generated by Django 6.0.1 on 2026-09-10 16:49

from django.db import migrations, models


def infer_category_type_from_history(apps, schema_editor):
    """Existing categories predate the income/expense split, so guess it
    from how each one was actually used: a category used only for income
    transactions becomes an income category; anything else (expense-only,
    mixed, or never used) stays the "expense" default set above, which is
    the more common case and easy to fix by hand in the rare mixed case."""
    Category = apps.get_model("budget", "Category")
    Transaction = apps.get_model("budget", "Transaction")

    for category in Category.objects.all():
        types_used = set(
            Transaction.objects.filter(category=category).values_list("type", flat=True).distinct()
        )
        if types_used == {"income"}:
            category.type = "income"
            category.save(update_fields=["type"])


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("budget", "0011_alter_budgetlimit_category_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="type",
            field=models.CharField(
                choices=[("income", "Income"), ("expense", "Expense")],
                default="expense",
                max_length=10,
            ),
        ),
        migrations.RunPython(infer_category_type_from_history, noop_reverse),
    ]
