# Generated by Django 6.0.1 on 2026-01-23 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='currency',
            field=models.CharField(choices=[('RON', 'RON (Romanian Leu)'), ('EUR', 'EUR (€)'), ('USD', 'USD ($)'), ('GBP', 'GBP (£)')], default='RON', max_length=3),
        ),
    ]
