# Generated by Django 6.0.1 on 2026-09-08 16:09

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_customuser_currency"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="image",
            field=models.ImageField(
                blank=True,
                default="default/user.jpg",
                null=True,
                upload_to=accounts.models.user_image_upload_path,
                validators=[accounts.models.validate_image_size],
            ),
        ),
    ]
